package io.github.pytgcalls.exceptions;

public class ConnectionNotFoundException extends ConnectionException {
    public ConnectionNotFoundException(String message) {
        super(message);
    }
}
